apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: taskvisualizerweb-env
  name: taskvisualizerweb-env
data:
  ASPNETCORE_ENVIRONMENT: "Production"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: taskvisualizerweb
  name: taskvisualizerweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskvisualizerweb
  template:
    metadata:
      labels:
        app: taskvisualizerweb
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              key: ASPNETCORE_ENVIRONMENT
              name: taskvisualizerweb-env
        image: taskvisualizerweb:latest
        imagePullPolicy: IfNotPresent
        name: taskvisualizerweb
        ports:
        - containerPort: 8080
        resources: 
          limits:
            memory: "128Mi"
            cpu: "500m"
