apiVersion: v1
kind: Service
metadata:
  name: taskvisualizerweb-external-frontend
spec:
  type: NodePort
  ports:
    - nodePort: 32124
      port: 4200
      targetPort: 4200
  selector:
    app: taskvisualizerweb-fe

---

apiVersion: v1
kind: Service
metadata:
  name: taskvisualizerweb-frontend
  labels:
    app: taskvisualizerweb-frontend
spec:
  selector:
    app: taskvisualizerweb-fe
  ports:
  - protocol: TCP
    port: 2531
    targetPort: 8080