apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  ports:
    - nodePort: 32123
      port: 8080
      targetPort: 8080
  selector:
    app: taskvisualizerweb

---

apiVersion: v1
kind: Service
metadata:
  name: taskvisualizerweb-backend
  labels:
    app: taskvisualizerweb-backend
spec:
  selector:
    app: taskvisualizerweb
  ports:
  - protocol: TCP
    port: 2531
    targetPort: 8080